### ISSUE TITLE
how to include this wonderful function in a CRAN package?

### ISSUE THREAD

**Issue by maxheld83** [briatte/ggcorr#6]
I'd love to use this function in a CRAN package, and give proper credit (of course).
Unfortunately, development on `GGAlly` seems to be slow/dead, and it doesn't have many of the bug fixes to `ggcorr` (such as #1), so the CRAN version is unfortunately unusable for me.

How do I do this? (I also raised this question in StackOverflow: http://stackoverflow.com/questions/30824419/whats-the-proper-way-to-handle-a-github-script-dependency-in-a-cran-package)

Any chance you might make `ggcorr()` into a proper package and release it on CRAN?
Maybe overkill for just one (wonderful) function ...

**Comment by maxheld83** [comment]
Alternatively, would you be ok with me "re-"-releasing your (current version) function as part of our [`qmethod`](https://github.com/aiorazabala/qmethod) package on CRAN?
(of course with proper information on the _actual_ author, you)

**Comment by briatte** [comment]
Hi @maxheld83,

I have just pushed the current version of `ggcorr.r` to the `GGally` repo, and would favour keeping it in `GGally`, since package maintainer @schloerke has kindly produced tests and improvements to that function, as well as one other contributor.

Sorry for the slow updates! And as far as I'm concerned, you should feel free to repackage the function if you feel that it would be useful to `qmethod` users. Please ask @schloerke for his position on that.

**Comment by maxheld83** [comment]
thanks, great!
I hope `GGally` gets to CRAN, soon – that would obviously be preferable.
Great work on `ggcorr`, again!

**Comment by briatte** [comment]
@maxheld83 You might be interested in trying out the [updated version of `ggcorr`](https://github.com/briatte/ggcorr) that I just finished committing. The current version does a few more things than the previous one, and should be 100% backwards-compatible (except for the default colors: I dropped the red-yellow-green scheme for a red-grey-blue one).

[There's also a vignette for it](https://briatte.github.io/ggcorr).

![](https://github.com/briatte/ggcorr/raw/master/demo.png)

The code has been submitted to the development branch of `GGally` and should end up in the CRAN package at some point.
